### ISSUE TITLE
🙋🏻Question: Primary, secondary and brand colours

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1232]
We currently use blue for the VF primary, and green for secondary. However for some "branded" components it's better to use the secondary green first. Would a brand colour help?

**Comment by sturobson** [comment]
Perhaps we can re-align (again) with corporate and have:

green as primary
blue as secondary
dark grey as tertiary

And give some good 'guide rails' as to when to use what button (for example) in what context. Some of this can then be written into the components.

**Comment by sturobson** [comment]
note: this might annoy teams using the CDN who had to switch this around the last time. 

So we'd need to give some sort of time frame for it.

**Comment by khawkins98** [comment]
It might be we're just overthinking it. For example: vf-navigation links are `--vf-theme--tertiary`:

![image](https://user-images.githubusercontent.com/928100/98947271-45b4db00-24f5-11eb-91f5-cd9f72323b57.png)

So then the default background for vf-header could be `--vf-theme--secondary`?

**Comment by sturobson** [comment]
A quick update to this - as I've gone 'gung-ho' and introduced something new to `vf-core`.

Previously we would declare the 'theme' of a component by having this class name structure - `vf-component-theme--`.

For `vf-card` and `vf-hero` I've moved to a more simpler `vf-component--`, so `vf-component--primary` etc.

In doing so, at the same time I moved towards what was listed above:

green as primary
blue as secondary
grey as tertiary

As we are starting with these refactored components having a 'limited' set of variants - we shouldn't rush into the confusion of – "why is this primary and this secondary". 

Well, we could, but the difference in the class name should help. 

This means we should be able to move forward with updating other components -- whilst keeping the older styles so there's no rush to fi things up.

**Comment by sturobson** [comment]
After the meeting this morning - it's clear that the change mentioned above 'jumped the gun' a little.

We discussed `brand` as a naming convention where we could still end up with `primary`, `secondary`, etc.

Whilst looking through the code I remembered a while back I introduced `theme-` as a design token. 

I'm thinking now that we could leverage this (after a bit of a re-write) to do:

`vf-theme--primary` - for more holistic theming of components, either locally or as part of their container (`vf-container-name--theme--primary` for example). 

This would leave us with `primary`, `secondary` as the 'function' of parts of the component (like buttons) and would save us trying to fathom a terse word of 'interactive'.

Thoughts?

**Comment by khawkins98** [comment]
This relates to #1236 and may become redundant once that is done.

**Comment by cindyebi** [comment]
Colour token updates:

Colours are now organised based on functionality instead of hierarchy: [Colours.pdf](https://github.com/visual-framework/vf-core/files/5814011/Colours.pdf)

1. **Primary Brand Colour**: Green 700 (#18974C)

2. **Links**:    
Normal state: change from Blue 600 (#3B6FB6) to Blue 700 (#2A57A3) for better legibility.
Visited state: change from Blue 600 (#3B6FB6) to Purple 900 (#2A57A3) for better legibility.

![Screenshot 2020-12-18 at 09 51 40](https://user-images.githubusercontent.com/75834903/104612059-b1463080-567d-11eb-9bed-937572f1389c.png)
_Previous Blue 600 link colour on white background did not pass the AAA standard._

<img width="1085" alt="Screenshot 2021-01-14 at 15 28 01" src="https://user-images.githubusercontent.com/75834903/104611497-19484700-567d-11eb-81e4-f564ab245899.png">
_New Link colour variants for different states_

3. **Buttons**:
Primary: 
• No changes on the Normal, Hover, and Focus states. 
• Added a Disabled or Inactive state colour.

Secondary:
• Change from the green with black text button style to white with a blue outline. The previous green button was ‘competing’ against the Primary Blue colour and there was no distinct visual hierarchy between the primary vs. secondary button styles.

<img width="747" alt="Screenshot 2021-01-14 at 15 29 36" src="https://user-images.githubusercontent.com/75834903/104611709-53b1e400-567d-11eb-966b-c9e302511e0a.png">
_Green with black text style variant vs. blue outline_

• Added a Disabled or Inactive state colour.

Tertiary Button: 
• Button colour change from Neutral 600 (#707372) to Neutral 800 (#373A36) for a better visual distinction between active vs. inactive button states. 
• Neutral 900 (#000000) as shadow colour.

4. **Error state**: change from #D32F2F to Red 800 (#B20C35) to keep it consistent with the primary Red palette.

**Comment by khawkins98** [comment]
Aside: @sturobson  with the new colour palette in https://github.com/visual-framework/vf-core/issues/1236#issuecomment-760117390 can we deprecate and start moving away from the UI colours?

I think our original usage of the UI colours were:

- no neutral light grey
- no light yellow for generic vf-banner
- no good red for warnings

I think the new graduated colour palette resolves all those.

**Comment by khawkins98** [comment]
Also, in the revised tokens rather than using the word "green" in the new primary brand colours:

https://github.com/visual-framework/vf-core/blob/a656c25307a78aabd06e678798730a37915f42fe/components/vf-design-tokens/src/core.palette.alias.yml#L3-L9

I'll suggest we call these `vf-color--brand--*`

**Comment by sturobson** [comment]
> can we deprecate and start moving away from the UI colours?

Yes! This is part of the reasoning behind asking Cindi to create a larger set of tint / shade stacks.

We can then remove any `set-ui-color()`, `ui-color()`, or `var(--vf-ui-color--nn)` and replace with the appropriate versions from the larger colour palette as needed.

**Comment by khawkins98** [comment]
Another thought: we add tokens for:

- vf-color--button--
- vf-color--link--
- vf-color--error--

**Comment by sturobson** [comment]
I think we're moving more towards an additional level of abstraction on all things:

global:
`vf-color--blue`

alias:
`vf-color--button`
`vf-color--button--secondary`

or something similar. 

I think we might have to move off of Theo and towards Style Dictionary. 

This can give us better benefits in a stricter naming convention of things because we could follow:

https://amzn.github.io/style-dictionary/#/properties?id=category-type-item

**Comment by cindyebi** [comment]
> Also, in the revised tokens rather than using the word "green" in the new primary brand colours:
> 
> https://github.com/visual-framework/vf-core/blob/a656c25307a78aabd06e678798730a37915f42fe/components/vf-design-tokens/src/core.palette.alias.yml#L3-L9
> 
> I'll suggest we call these `vf-color--brand--*`

Sounds good, let's call it "Brand" instead of "Green" then.

**Comment by khawkins98** [comment]
I believe we've now accomplished this. Closing. 

Please reopen if required.
