### ISSUE TITLE
Discussion: standardise colour tint stacks

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1236]
(Adding this from a discussion by @sturobson on Slack)

Some of the current colour lightest, light, normal, dark, darkest tints aren't smooth steps. For example, the greys: 

![image](https://user-images.githubusercontent.com/928100/99141683-14035780-264e-11eb-9c11-9a269d33bc96.png)

- https://latest.visual-framework.dev/design-tokens/colours/

Could these be standardised?

https://codepen.io/sturobson/pen/add353ccd4deeef34e9679abdc8a2c6a?editors=1100

Related: #1232 (Primary, secondary and brand colours)

**Comment by khawkins98** [comment]
@cindyebi has been spending time working on the colours and scales, handing this off.

**Comment by cindyebi** [comment]
Colour token updates:

- Colours are now organised based on functionality instead of hierarchy: will be discussed on #1232 separately 
- Added a standardised Colour Palette stacks, created from the existing primary and brand colours: [Colour Palette.pdf](https://github.com/visual-framework/vf-core/files/5813881/Colour.Palette.pdf)
- Shade naming convention: "Shade Name #000", for example: Blue 700, Red 100, Neutral 600 for intuitiveness and ease of use
- Change of the EMBL Light Grey Tint (#A8A99E) to Neutral 400 (#A9ABAA) for shade consistency

Link to the **Design Library on Figma**: https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=5%3A39

**Comment by khawkins98** [comment]
I think this has been achieved by @cindyebi and @sturobson work. Closing. 

We still need to implement the shades in the tokens (https://github.com/visual-framework/vf-core/blob/develop/components/vf-design-tokens/src/core.palette.alias.yml), but that can be picked up in #1232
