### ISSUE TITLE
Consistency: "read more" links

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1287]
We inconsistently approach "read more" links in our pages. 

We discussed this briefly in our [8 Dec 2020 UX clinic](https://docs.google.com/document/d/1200GecXZZbIzHJ3HQ2ygY5NIYwQDyRVhfP21iscP7Y8/edit?pli=1#heading=h.vdftb4fmed18) 

- Niki point out that where possible to avoid text like "Read more" and instead let in-context links drive the conversions;  
https://www.nngroup.com/articles/learn-more-links/ 
- I noted that we already have our [vf-section-header](https://stable.visual-framework.dev/components/vf-section-header/#vf-section-header--is-a-link) that we use fairly consistently

My suggestion would be to avoid using "read more" links and see how well our vf-section-header can perform it's job.

Thoughts?

---

### Sometimes it’s a button

![image](https://user-images.githubusercontent.com/928100/101515919-2b98dc00-397f-11eb-9d9a-9d77c9b1b8dd.png)
EMBL.org/about

### Sometimes it’s on the left

![image](https://user-images.githubusercontent.com/928100/101515884-22a80a80-397f-11eb-948f-4d1e31c25b16.png)
EMBL.org/research

### Sometimes there’s no button

![image](https://user-images.githubusercontent.com/928100/101515848-1a4fcf80-397f-11eb-896b-67a09ef53f77.png)
https://wwwdev.embl.org/groups/cuylen/

### Sometimes it’s text

![image](https://user-images.githubusercontent.com/928100/101515809-0e640d80-397f-11eb-97d2-e4fb7e78fc1b.png)
https://wwwdev.embl.org/about/info/communications/

### The section header itself is a “readmore” 

![image](https://user-images.githubusercontent.com/928100/101515776-04420f00-397f-11eb-94d5-8537964c86de.png)

**Comment by sturobson** [comment]
I've always felt the Neilson research was more to do with text that is links rather than call to action buttons … of course - we have both of those here too

**Comment by khawkins98** [comment]
Yeah, i think that's a good distinction. A "call to action" is something we still want to do, so ...

- "Read more": Don't do 'em
- "Call to action": Yes

But what do they look like?

- Should be highly visible, so probably `vf-button` (primary and not small)
- Positioning: left, right, centre?

**Comment by nikiforosk** [comment]
Just to follow up, I think that we should review these examples on a case by case basis as they are a mixture of improving the copy, the layout and the call to action. As a first attempt to do this:

1. The "Apply now" button below the job description in the examples that you shared above is redundant (especially given that it is the same link as the link on the title of the job description). This is one of the issues flagged by the NN article I shared.

 ![image](https://user-images.githubusercontent.com/20280139/101637684-fba41400-3a24-11eb-9c09-ba877cdcad8c.png)

2. In some cases, e.g. when there is a long list of jobs and we'd like people to view more of them, it would be reasonable to have a call to action for that further down the page (especially if the section header that does the same job is out of view) as in the 2nd "Latest jobs" example that you shared. 

 ![image](https://user-images.githubusercontent.com/20280139/101638443-fbf0df00-3a25-11eb-8f16-c8cbecf4ce67.png)

In that case, instead of just "Show more", we'd like to have something more descriptive such as "Access all jobs at EMBL", "Browse all jobs at EMBL" or "Explore all jobs at EMBL" as NN also suggest.

At the moment we use "Show", "View" or "See" but this not as applicable to people who use screen readers (similarly to [the "Click here" antipattern](https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/)).

3. Whether this is a button or link, I think, depends on whether this is the main CTA on the section or the whole page. I think it's reasonable to vary this to reflect the importance of this particular CTA in the context in which it appears.

4. It is recommended to [left-align elements in forms](https://adamsilver.io/articles/where-to-put-buttons-on-forms/) and [more generally in layouts for improved accessibility](https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/) so I'd expect this to be left aligned as in the second "Latest jobs" example that you shared.

**Comment by nikiforosk** [comment]
A separate observation which is probably a topic on its own:

Is it "Latest Jobs" with capital J (title case) as in the first screenshot or "Latest jobs" with small j (sentence case) as in the second one?

**Comment by sturobson** [comment]
> Is it "Latest Jobs" with capital J (title case) as in the first screenshot or "Latest jobs" with small j (sentence case) as in the second one?

I think it would be sentence case – Latest jobs. 

As a fan of Title Case - I started using it for most things in `vf-core` before I was … 'reprimanded' (in the loosest of ways).

**Comment by nikiforosk** [comment]
Title Case Can Go Wild...

but sentence case also has issues: Are job titles in the job descriptions such as Content Team Lead proper nouns?

which reminds me: Where is our styleguide?

**Comment by khawkins98** [comment]
Another one spotted on https://www.embl.org/sites/grenoble/

![image](https://user-images.githubusercontent.com/928100/102382798-206f2d00-3fcb-11eb-975f-7d5187d83891.png)

Here the use case is a bit of a "related: you might also like all EMBL news"

**Comment by sturobson** [comment]
I think if we've make sure that interactive elements are blue -- then the heading with the arrow should be enough.

If not - the heading should stop being a link with the arrow -- which would impact other use cases. 

I think things like 'see more new from across EMBL' need to go.

**Comment by nikiforosk** [comment]
> I think things like 'see more new from across EMBL' need to go.

I agree, I feel that if I'm at EMBL Grenoble then I expect to see news from EMBL Grenoble. 

The "more of the same from EMBL" presumably is an attempt to explain that "Grenoble is one of the six EMBL sites, and we have whatever is featured in this section across EMBL too" but this doesn't look like a good way to explain the relationship between a site and the wider organisation (in fact it may even confuse people who are not aware of it).

**Comment by sturobson** [comment]
> I think things like 'see more new from across EMBL' need to go.

I actually misread the link - in that it was duplicated what "News from EMBL Grenoble" was doing.

**Comment by khawkins98** [comment]
Based off conversations some guidance we could include in high level dos/donts of the VF at https://latest.visual-framework.dev/guidance/:

> "Read more" and "click here to learn more" links at the end of already-linked content should not be used. They add additional cognitive complexity and creates uncertainty for users on what to click and if links go to different locations. More background is [available in the GitHub discussion](https://github.com/visual-framework/vf-core/issues/1287).

Instead of a stand-alone guidance, this could be the anchor of a web-specific style guide (other topics: opening in new windows, email links, and similar)

**Comment by khawkins98** [comment]
Closing this as we now have https://stable.visual-framework.dev/guidance/content-guidelines/#read-more

Extract:

> It's common to see phrases like "read more" and "click here" at the end of a section or container. These typically provide sub-optimal user experiences and lower conversion rates. It's better to add links within the content itself.

Please reopen if you think we need more guidance, other wise I think we now "only" need to proceed by removing some the extraneous "read more" links on our many pages.

**Comment by sturobson** [comment]
👍 

I think we still need to review and create guidelines for some microcopy usage though

- use `apply now` for buttons on jobs
- Is `see more jobs` inclusive?
- what text should be used for often used 'read more' style text links
- search / search now / filter -- what/when to use
- fieldset legends for forms
- latest news or latest updates 

etc. etc.
