### ISSUE TITLE
Component: form nesting

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1347]
I was discussing [on Slack](https://visual-framework.slack.com/archives/C01G2RX3ZV5/p1612167531001400) about the use of indented fieldset forms on the dev training site.

![image](https://user-images.githubusercontent.com/928100/106731571-e8ba5400-660f-11eb-9b1a-23d7d9716679.png)

1. Current [vf-form docs](https://latest.visual-framework.dev/components/vf-form/vf-form__core/) don't offer much in the way of fieldsets
2. Need here is to show clear groups of sub elements
   > From @cindyebi The indent is suppose to visually show which filter options belong to which category, in this case the labels “On-demand training” and “Live-training” do not have any caret or the expand icons so when put on the same line they look just like a long list. Can be discussed further when we meet again.
3. How can we best achieve this grouping; some common approaches:
  - indentation
  - outlines
  - collapsable (js, yuck)
  - vertical spacing

## Related issues from search

- Enhancements for vf-form #762
- vf-form refactor #820

**Comment by sturobson** [comment]
> Current vf-form docs don't offer much in the way of fieldsets

As mentioned, I think the form documentation needs to be split out so that each component has it's own little Idaho of guidelines, this will help with the fieldsets (I'm guessing the fieldset guidelines will mimic the HTML spec, as there's nothing really more to add)

> show clear groups of sub elements

This makes the design a little 'off centre' I think we need to look at creating a 'facet' that can show/hide this content. From previous experience this parent component 'wrapper' was user tested and the way forward where there is chance for several potentially long lists of filters in a search results page. Rather than indent - a new pattern is required, which might tie nicely with fieldset usage.

How can we best achieve this grouping; some common approaches:

collapsable show/hide -- the JS is only a 'yuck' if we don't progressively enhance the component for when JS files.

**Comment by khawkins98** [comment]
> collapsable show/hide -- the JS is only a 'yuck' if we don't progressively enhance the component for when JS files.

Driveby thought that `details` + `fieldset` might be a useful combination, a quick look suggests it's valid markup and might fit the use case and without JS.

**Comment by nikiforosk** [comment]
Two quick thoughts:

1. Given that we're short of horizontal space, [the Gestalt psychologist](https://www.usertesting.com/blog/gestalt-principles) in me thinks that we should be relying more on proximity (i.e. put things that should be perceived as a group closer together) and typographical hierarchy (to make sure that elements which are at the same level look the same and are distinct from elements at different levels). The hierarchy is already there, I think, but maybe we can tweak a bit the vertical spacing to make the groups more distinct.
 
2. The collapsable element of the filters with the caret is to address the issue that some filter groups (such as live training) take a lot of vertical space and you may need to scroll down a lot to find the next group (or might not notice the additional filters  at all if you're focusing on the search results on the main part of the page). I don't think that we should be relying on this to signify grouping or hierarchy but use proximity and typographic scale instead.

The fact that this will also make the filters on the side behave like an accordion [may also be problematic according to our gurus in NN](https://www.nngroup.com/articles/accordions-complex-content/). Perhaps it might be better long term to place the filters above the search results as Cindy proposed in [her designs for the Training site](https://www.figma.com/file/rCmmqJ4ZdH5KweCBxoXu4u/Training-Academy-Mockups?node-id=34%3A490).

**Comment by sturobson** [comment]
Along with my previous experience of working on complicated search results showing that, after user testing, the idea of show/hide–ing the filters in a left column works (and it's still there, 5 years later) - it's a similar technique that's currently used for filtering results on eBay. 

If it goes above - then all filtering for all of EMBL things should go above to keep with a [unified](https://latest.visual-framework.dev/design-principles/#Unified) and [ingrained](https://latest.visual-framework.dev/design-principles/#Unified) larger design system.

**Comment by sturobson** [comment]
… just in case there's some confusion - the filters would be visible on page load, then have the option to hide by the sites visitor. So they can:

- still scroll the page to see all the options 
or 
- hide a filter (or filters) to bring up what filters are below it.

Definitely don't load the page with all filters hidden., the antithesis of the show more component.

**Comment by sturobson** [comment]
A quick note to say we have precedent here with the [job listings](https://www.embl.org/jobs/#group=data-group-1&location-barcelona=0&location-embo=0&location-grenoble=0&location-hamburg=0&location-heidelberg=0&location-hinxton=0&location-rome=0&type-adm=0&type-bio=0&type-com=0&type-dtc=0&type-fac=0&type-gen=0&type-its=0&type-oth=0&type-pos=0&type-pre=0&type-res=0&type-sde=0&type-sss=0&type-tec=0&type-tra=0&type-trn=0) - If we change to ‘nesting’, we need to change all instances so that we’re [syncronised](https://latest.visual-framework.dev/design-principles/#Syncronised) and [unified](https://latest.visual-framework.dev/design-principles/#Unified)

**Comment by sturobson** [comment]
With the latest release of `vf-form` things with updates to `vf-fieldset` and documentation of what can/should go where. I'm gonna close this one.
