### ISSUE TITLE
Idea: ship a full VF build to npm with vf-component-rollup

### ISSUE THREAD

**Issue by gustavo-salazar** [visual-framework/vf-core#1409]
Hey there,

Not sure if this is the place to ask this, so please redirect me if necessary.

So, we are using the CSS from the `emblstatic` CDN recommended in option 1 of your building page.
I'm wondering if that is available in one of the npm packages? As I would prefer to take it from npm to make it part of our periodical update of dependencies. This will also allow us to include the file in our bundled, without the extra processing of sass files.

Thanks,
Gustavo.

**Comment by sturobson** [comment]
Hi Gustavo! 

Thanks for the question.

Currently this is something not provided in the `vf-core` codebase.

The Sass config files, and each component is available as a separate npm package that you can then 'pick and choose' to what you need in your project.

This should be easier to maintain in the long run.

`vf-core` still has some components that change relatively quickly, so it might be more advantageous to go this route as you can then update the node package as you're ready too, component by component rather than the potential need to refactor lots of things if you have one CSS file.

Does that make sense? I'm happy to jump on a call to discuss further - ping me an invite - stu.robson@embl.de 

@khawkins98 also might have some (clearer) thoughts :)

**Comment by khawkins98** [comment]
Hrm, interesting idea.

The released CSS is a bit of an artefact of "all the things" but particularly the combination of:

- the VF Sass and JS build processes
- vf-component-rollup (the referenced CSS and JS)

If we did release the compiled CSS to npm:

1. the build process would (also) need to output the CSS and JS into `./components/vf-component-rollup`
2. we would need to match the VF version to vf-component-rollup

I don't think that would be too hard but we'd want to think if it's "correct" to do so and if there's any knock-on effects.

---

I've just seen @sturobson 's response pop in: I would agree it's best to build your own CSS, as then you'd have complete control. But I could also see an appeal of this ... 🤔

**Comment by gustavo-salazar** [comment]
Thanks for the info.

I get the point from @sturobson of the benefits of using it from the packages, I tried including the sass files and processing them on our side, but I had multiple issues in the build. So I thought it wasn't worth to put so much time on it, when I can just directly get the CSS. Lazy me 😅
And it works, I'm using it from CDN and using the `vf-` classes and it's looking good. Thanks for the good job.

I would just like to take it from a repo to have control on updates and thought that given that you are producing the files anyway it might be part of a repo already.

**Comment by khawkins98** [comment]
Thinking on this a bit more, we would also need to ship the various assets (svgs, png, woff, etc) to npm. It will probably be a couple of weeks before we'd be able to look into any features changes for this. 

In the meanime, I (and I'm sure Stu, too) would be happy to help getting a local Sass build working.

**Comment by khawkins98** [comment]
Relates to #1250

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
