### ISSUE TITLE
Component: "super navigation" mega-menu-style component

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1718]
In #1621 and #1622 as well as the [VF July sprint](https://docs.google.com/presentation/d/1I8t3A6FId5FmdYpyKD9K-8gtKelcUnwTO6hqsSKnS-o/edit#slide=id.p14), our investigations pointed to the need for a mega-menu-style component. 

This component would allow navigation items to be clicked on and insert/show a horizontal container.

## Standard questions

- In a few words, what does this component look like?
  <img width="1824" alt="image" src="https://user-images.githubusercontent.com/928100/140738771-44bbb489-f044-4432-8dd5-392cae41a4ea.png">

- In a few words, what does this component do?
  Show horizontal-containers, primarily for navigation. There is a conceptual overlap with vf-tabs and vf-dropdown.

- Would a rebrand change the structure or layout of this component?
  Not likely.

- Can other websites use this component? Or is it only useful in your organisation or website?
  Others could use

- Do you have any designs or concepts?
  @cindyebi is working on them

- Have you done any user testing already?
  no

- How often do you expect to make use of this component?
  Most pages would have one, coming from the global page template.

- Can you list out major elements in this component?
    - clickable item
    - revealed container

- Will all elements of this component be used every time?
  Generally yes

- Does this component contain other components?
  Uncertain

- Do you already have a component?
  @nitinja is working on a barebones example

## Any further thoughts?

While the UX and design guidance will say how this component _should_ be used, in principle it could be used to show any container.

A few practical questions:

1. Does the revealed content appear "over" the existing content, or push content down?
2. Could we reuse vf-tabs somehow?
3. The JS could attach to any element to show any element

**Comment by nitinja** [comment]
Hi, note that till we make any ux prototype, I am following UK gov megamenu as a n example implementation https://www.gov.uk/government/organisations

**Comment by cindyebi** [comment]
2-level navigation hierarchy:
![2-level](https://user-images.githubusercontent.com/75834903/140917148-20c9a9c1-58d4-4da2-934f-7fe05a8d914d.png)

3-level navigation hierarchy:
![3-level](https://user-images.githubusercontent.com/75834903/140917754-9f4c63d9-2096-46e8-8bed-d562ab0445df.png)

Search:
![Search](https://user-images.githubusercontent.com/75834903/140917154-7dee6726-9e91-4a14-b61d-35d89f07cae8.png)

Notes:
• We discussed this morning about combining the 2 and 3 hierarchy levels within the menu. If we decided to use the section header layout, let's keep it consistent for all menu items to use the same. 
• Navigation item that has an expandable [mega] menu will have a caret icon next to the label as a signifier. The caret icon will state the available user action, e.g. pointing down when the menu is closed and pointing up when the menu is opened. 
• Mega menu items will be displayed in blue to signify clickable links.

**Comment by khawkins98** [comment]
I'm thinking about that green line, which also exists similarly on the top of vf-footer. Thinking it could be componentised as a `vf-divider--enclosure` or something like that.

<img width="1768" alt="image" src="https://user-images.githubusercontent.com/928100/140919335-1854da1a-83a5-4a3a-ab2d-cf10bbab5c9a.png">

**Comment by khawkins98** [comment]
Technical thoughts on the caret in the navigation, this could be appended by CSS with something like:

`.vf-megamenu.vf-megamenu__activated .vf-navigation__link.vf-megamenu__item--has-section`

**Comment by khawkins98** [comment]
The menu entries could be `.vf-mega-menu__toggle`

<img width="188" alt="image" src="https://user-images.githubusercontent.com/928100/140920377-6c5ced3d-dd3b-4483-b56e-a07104f16e6f.png">

And the megamenu that activates could be `.vf-mega-menu__section`

**Comment by nitinja** [comment]
@khawkins98 thanks, I am thinking something similar

**Comment by cindyebi** [comment]
I added an overlay so when the mega menu is active, it is in focus. Unless the mega menu is covering up the entire page, we don't need the overlay.

![3-level](https://user-images.githubusercontent.com/75834903/141287589-96c31df8-76c9-4824-bd9f-77ed6da4b224.png)

![Search](https://user-images.githubusercontent.com/75834903/141287593-3b5487cc-c946-4f3f-947a-8463370fb9ac.png)

![2-level](https://user-images.githubusercontent.com/75834903/141287581-5739efed-d1da-4d2d-ab29-f0fe72d8ef19.png)

**Comment by cindyebi** [comment]
Mockup on how it looks like on the COVID-19 data portal:
![3-level-covid19](https://user-images.githubusercontent.com/75834903/141321228-7c724b4e-de4d-4c6f-8a18-87db5c24db0c.png)

**Comment by OliveiraCs** [comment]
Mockups EMBL-EBI Corporate site:
IA to be reviewed( in progress)

![EMBL-EBI_megm-v2 3-level](https://user-images.githubusercontent.com/93318924/141334816-dcb3e67c-70c1-4ff3-9e17-f39fad5e1643.png)
![EMBL-EB_megm_3-level](https://user-images.githubusercontent.com/93318924/141334824-a943662d-5ef2-4296-a645-ad7c838d6ba0.png)
![EMBL-EBI_megm-2-level](https://user-images.githubusercontent.com/93318924/141334826-4c48bcdc-e1c9-4e9e-b2e1-f986702f7604.png)
![EBML-EBI megamenu 3-level](https://user-images.githubusercontent.com/93318924/141334833-02527386-0909-45bb-b221-ede71acfed31.png)

**Comment by cindyebi** [comment]
Mobile version:
• Homepage: instead of using a hamburger menu, it is recommended to use the label "Menu" for better discoverability. It's also adopted by the [gov.uk](https://www.gov.uk/) site. 
<img width="375" alt="Homepage" src="https://user-images.githubusercontent.com/75834903/142843250-bb08170b-4aa4-46bb-9563-c9027a74a4ab.png">

• Search is separate from the main Menu and once expanded uses the [vf-search-mini](https://stable.visual-framework.dev/components/vf-search/index.html?q=search#vf-search--mini) component that was designed specifically for mobile or small screen sizes.
<img width="375" alt="Search" src="https://user-images.githubusercontent.com/75834903/142843262-bf473ed1-287a-4dc6-8a93-a2c512458cf6.png">

Menu - Expanded: shows the first level navigation menus using an accordion or similar to the [vf-details](https://stable.visual-framework.dev/components/vf-details/index.html?q=details) component. Menu options are labeled in [link](https://stable.visual-framework.dev/components/vf-link/index.html?q=link#vf-link--example) blue to signify clickability.
<img width="375" alt="Expanded 1" src="https://user-images.githubusercontent.com/75834903/142843268-cdb9b35d-34ee-40d6-b7f4-9f6bfae5caab.png">

Menu - Expanded 2 v1: shows the second level navigation menus with slight indentation to have a better visual distinction between each hierarchy. 
<img width="375" alt="Expanded 2 v1" src="https://user-images.githubusercontent.com/75834903/142843282-c7714bd2-c03a-4eb9-aaeb-ccc1b4929a88.png">

Menu - Expanded 2 v2: shows the second and third level navigation menus with scrolling behaviour to reveal the rest of the menu. 
<img width="375" alt="Expanded 2 v2" src="https://user-images.githubusercontent.com/75834903/142843292-00cb340d-4032-46e6-880c-6416231da7c3.png">
