### ISSUE TITLE
Clickable images in the news feeds

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-core#1750]
We've received multiple suggestions from users to make the images in the news feed clickable, especially in the [vf-news-container--featured](https://stable.visual-framework.dev/components/vf-news-container/#vf-news-container--featured) variant.

I remember that this topic was raised at the very beginning of embl.org but I don't know why this hasn't been implemented. Would there be any 'No' for that?

Thanks!

**Comment by nikiforosk** [comment]
The main reason not to do that from an accessibility perspective is to avoid "redundant link" alerts which are triggered when adjacent links go to the same URL (in that case the link on the image and the title of the article would be the same). 

When adjacent links go to the same location this results in additional navigation and repetition for keyboard and screen reader users.

Also images that act as links need alt text (which is actually redundant because most of these images are decorative).

The best practice in that case is **for the image and the title of the article to be combined in one link** (which is how vf-cards work).

I attach a screenshot [from the w3 guidelines with the relevant example highlighted](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html):

![w3-link-purpose-Screenshot 2022-01-27 at 15 23 10](https://user-images.githubusercontent.com/20280139/151390449-87cfa483-49b7-481d-8d93-3e092d91ed7b.png)

And another one with the summary of the guidelines from a similar example [on a page evaluated by WAVE](https://wave.webaim.org/report#/https://wwwdev.ebi.ac.uk/training/online/courses/bioinformatics-terrified/):

![redundant-link-wave-Screenshot 2022-01-27 at 15 27 27](https://user-images.githubusercontent.com/20280139/151390528-aac306c8-178d-4bc2-af1d-02e22be0ce7d.png)

I hope this is useful, please get in touch if you'd like to discuss this more.

**Comment by nikiforosk** [comment]
The news summaries in [the BBC news](https://www.bbc.co.uk/news) are applying this best practice - the image and the text below it are one link:
![bbc-news-iamge-text-link-Screenshot 2022-01-27 at 15 51 23](https://user-images.githubusercontent.com/20280139/151394759-0eef05bd-77b2-4647-a34a-cf7cc98582c0.png)

**Comment by khawkins98** [comment]
Hi there! Writing to second @nikiforosk's take that using the vf-card's technique of making the title link cover the clickable area is the better approach.

There will be some gotchas around how to handle other links in the news items, but again you can look to vf-card for an approach.

https://stable.visual-framework.dev/components/vf-card/

![grafik](https://user-images.githubusercontent.com/928100/151627363-7eb210dd-1b99-4746-959c-8d2074539574.png)

![grafik](https://user-images.githubusercontent.com/928100/151627313-201e01d3-3c6a-4a40-aedf-30acc484e6fe.png)

**Comment by nikiforosk** [comment]
@sandykadam to ask Maged to look into this at content hub.

**Comment by sandykadam** [comment]
@nikiforosk I checked this on my local and doesn't seem to be that easy as it contradicts with VF core principles of implementation. So we should hold this until we have PD and this also requires changes in  VF core.

I tried to implement what Ken suggested in previous comment, but code wise it looks mixture of summary & card which I think is not the correct way and also the display looks weird.

![Screenshot 2022-11-11 at 12 20 49](https://user-images.githubusercontent.com/1227241/201339666-56c297c0-107f-4979-be19-25a9725d6636.png)

In above screenshot if you see first box we are achieving the whole block clickable with mixture of vf-card & vf-summary but at the same time display looks bit different.

This is the code to achieve to make it work:
```
    <article class="vf-summary vf-summary--news">
      <img src="https://stable.visual-framework.dev/assets/vf-summary/assets/vf-summary--news-has-image.jpg" alt="" class="vf-summary__image" loading="lazy">
      <div class="vf-card__content | vf-stack vf-stack--400">
        <h3 class="vf-card__heading vf-summary__title"><a class="vf-card__link" href="JavaScript:Void(0);">some news heading
        </a></h3>
        <span class="vf-summary__date">4 September 2019</span>
      </div>
    </article>
```

We might have to introduce new varient in vf-summary and for this we will need proper change in VF core.

**Comment by nikiforosk** [comment]
I just noticed that [the vf-video-teaser](https://stable.visual-framework.dev/components/vf-video-teaser/) shows the desired behaviour, i.e. when I mouse over the image the link underneath it is highlighted:

![Image](https://user-images.githubusercontent.com/20280139/223774318-c3cc0e2b-cc58-4e84-bd99-c36b83e574ff.png)

**Comment by Adedoyinebi** [comment]
@bhushan-ebi as we discussed during the sprint planning meeting, I have done further investigation as to what the best practice recommendation will be to address the issue of redundant links in the [vf-news-container](https://stable.visual-framework.dev/components/vf-news-container/#vf-news-container--featured). 

**Best practice recommendations**

- From my investigation it is recommended that both links both elements should be wrapped in the same link. Here’s an example code:

```
<a href="home.html">
  <img src="house.gif" alt="home page icon">
  Go to the home page
</a>
```

- In a case where the descriptive text on the image is a repetition of the adjacent text, it is recommended to use a null alternative text on the image:

```
<a href="products.html">
   <img src="icon.gif" alt="">
   Products page
 </a>

```

**Useful reads**

- [How redundant links impact accessibility | Bureau of internet accessibility](https://www.boia.org/blog/how-redundant-links-impact-accessibility)
- [Combining adjacent image and text links for the same resource | W3C](https://www.w3.org/TR/WCAG20-TECHS/H2.html)


**Next steps**

- Kindly update the [vf-news-container](https://stable.visual-framework.dev/components/vf-news-container/#vf-news-container--featured) to have both the image and the text wrapped in the same link. 
- The behaviour on hover should be similar to the [vf-video-teaser](https://stable.visual-framework.dev/components/vf-video-teaser/) as shown in Niki’s message above. Where the link gets highlighted on hover.
