### ISSUE TITLE
Improvements on examples of vf-link

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1912]
- [ ] Colour of visited link [in html examples](https://latest.visual-framework.dev/components/vf-link/index.html?q=link#vf-link--example) is `#734595` but the Link Visited Colour in the design tokens is `#563D82`. Change the colour of visited link to `#563D82`
- [ ] The underline on mouseover of the examples makes it harder to identify the state: could it be applied to the mouseover state only?

**Comment by Adedoyinebi** [comment]
**Current state**

For the current [examples of vf-link](https://stable.visual-framework.dev/components/vf-link/#:~:text=Examples-,Example,-A%20text%20link), the other states are shown without any need for interactions such as clicking or hover, however for the example of the link on hover:
- Requires an hover interaction before the sample is displayed
- Shows the hover colour #193F90 (--vf-color__link--hover) before and after hovering.

![Image](https://github.com/visual-framework/vf-core/assets/126486114/68bc9d2c-2c65-4935-83db-d4700492135f)

**Desired behaviour and proposed solution**

- The example for the hover should show the the hover link colour #193F90 and the link underlined so that it is consistent with the pattern of other examples

**Figma design**

- [Link to figma design](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?type=design&node-id=486%3A546&mode=design&t=CkiZmGglkDRFWWT7-1) showing the link example on hover.



![Image](https://github.com/visual-framework/vf-core/assets/126486114/8426dbb6-5bc7-4222-a0f1-3d8ffb40a880)

@stefangutnick Please review this

**Comment by Adedoyinebi** [comment]
I am leaving this issue open to subsequently address the other identified issues in the link examples discussed in todays standup, this issues will be picked up in the next sprint:

**Next steps**

The current the disabled link in the [vf-link](https://stable.visual-framework.dev/components/vf-link/#:~:text=Examples-,Example,-A%20text%20link) examples shows in blue **#3b6fb6** which is the same colour as the normal link. 

- Investigate the colour disabled link example in HTML and Figma and provide best practice recommendations
- Check effect if implementing the update to ensure no existing service sites using links would break

The Visited link [example](https://stable.visual-framework.dev/components/vf-link/#:~:text=Examples-,Example,-A%20text%20link) shows a different colour (**#734595**) from the defined token (**#563D82**) for visited links

- Investigate the colour of visited link examples in HTML and Figma and provide best practice recommendations
- Check effect if implementing the update to ensure no existing service sites using links would break

**Comment by Adedoyinebi** [comment]
Based on our discussion during the Sprint review meeting and best UX practice, we agreed to remove the disabled link from the [vf-link examples](https://stable.visual-framework.dev/components/vf-link/#:~:text=Examples-,Example,-A%20text%20link)] as disabled links present usability and accessibility issues some of which are summarised below:

- Users find it difficult to troubleshoot (Why is the link disabled?)
- They are not accessible when using tab to navigate through a webpage
- The current example shows a disabled link in the same colour as a regular link which can be confusing to users

**Useful reads**

- [Usability pitfalls of Disabled Buttons, and how to avoid them - Smashing magazine](https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/)]

**In addition**

1. To ensure consistency with the defined **$vf-color__link—visited token**, the colour used for the Visited link example should be updated from **#734595** to **#563D82** as defined in [the tokens](https://stable.visual-framework.dev/design-tokens/theming/#:~:text=vf%2Dcolor__brand%2D%2Ddark-,Text,-Primary%20Text%20Colour)]. 
2. The examples shown should be improved by using consistent interaction patterns all through (Show all example without requiring interaction e.g clicking - for visited link or hovering - link on hover). The language should also be clear, addressing the current state of the link examples. See [mockup in figma](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?type=design&node-id=548%3A9&mode=design&t=7AgSDo8ybIZsnKBz-1)] showing the updated examples for vf-link.

**Useful links**

- VF-link example [mockup in figma](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?type=design&node-id=548%3A9&mode=design&t=7AgSDo8ybIZsnKBz-1)]

@stefangutnick Kindly review this task

@bhushan-ebi A development task has been created for this: **Implementation of improved vf-link examples**
[#2030](https://github.com/visual-framework/vf-core/issues/2030)

![Image](https://github.com/visual-framework/vf-core/assets/126486114/8d0324d9-af80-4778-8a8a-91aac024139f)

**Comment by stefangutnick** [comment]
@Adedoyinebi Looks good to me. A very good change overall.
