### ISSUE TITLE
PATTERN: Messaging

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#26]
Now that we've begun to implement the vf-data-protection-banner, it surfaces some thoughts that will be common across many types of messages on sites:

1. Methods to show site wide messages in a "vf-site-messaging" container 
1. Check if a message is displayed/should be displayed
1. Show local site messages and/or [remote messages](https://dev.ebi.emblstatic.net/announcements.js) (EMBL specific sub-pattern?)
1. Handled message priority (notice | alert | warning | action-required)
1. Cookie management
1. Mechanisms for local sites to override any/all

Each of those might be sub-tickets...

**Comment by sturobson** [comment]
Could we have a generic 'alert' and 'banner' pattern? 

options:

positioning: top, bottom, middle
colours: red, green, amber, black/dark-gray
text: left-aligned, centered
grid: just use vf-grid for layout

I see an alert being something that would be more 'floating' rather than fixed to top or bottom of page.

**Comment by sturobson** [comment]
Ah, found this after creating #62

**Comment by khawkins98** [comment]
Eclipsed by the above. Closing.
