### ISSUE TITLE
Chore - Make use of .yml for adding in data/content

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#316]
There are a few patterns still that have 'hard-coded' content betwixt the HTML declarations. We need to move this out to the .yml file so that the patterns can be imported/included as needed in a SSG-site or single page boilerplate. 

- [ ] put all content in the .yml file
- [ ] make use of the .yml file to 'create' the variants of a component - rather than having several 'types' or if/else statements in the `view` template.

**Comment by khawkins98** [comment]
Tasks to be done:

## YAML and Nunjuck-ise  all the components

Rather than list each component, maybe we can approach each "tier" as PRs:

- [ ] All vf-elements
- [ ] All vf-blocks
- [ ] All vf-components
- [ ] All vf-containers
- [ ] All vf-grids (is there anything to do here?)

- [ ] All embl-elements
- [ ] All embl-blocks
- [ ] All embl-components
- [ ] All embl-containers
- [ ] All embl-grids (is there anything to do here?)

## Documentation

Probably a few types of documentation.

- [ ] High level on the role of components as "real" templates
- [ ] Building a component with .njk + .yml 
- [ ] Consuming a component's template

## Templating

- [ ] Update the component generator

**Comment by khawkins98** [comment]
We've (mostly you @sturobson) have made a lot of progress on updating components and I think this will be an ongoing process as we make new components and use components in sites. 

That is: we'll never fully "finish" this and we won't forget this, so closing.
