### ISSUE TITLE
QUESTION: As we cannot rely on `vf-body` being on the body element - what should we do?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#36]
Taking a look at [the landing page demo](http://dev.beta.embl.org/cancer/) we can see that the intended `vf-body` class is not on the `<body>` element.

At the moment there are a few things that rely on this (`vf-global-header`) for one.

Because of this - there's two options

1. As we cannot rely on it being on the body, remove it and adjust the vf-grid and embl-grid accordingly

2. Make it a requirement that the `<body>` has a `vf-body` class tacked on to it.

3. Do something else.

**Comment by khawkins98** [comment]
I think we could make it a requirement that `.vf-body` be a parent of a pattern, but not on a specific element, like `body.vf-body` 

We won't always be able to guarantee that `body.vf-body > .vf-global-header` ... often it might be `body.vf-body > div > span > godknowswhatelse > .vf-global-header `

Aside: I think the `.vf-header` grid takes priority over `.vf-body` for the `.vf-global-header` ([pattern](http://dev.beta.embl.org/guidelines/visual-framework/dev-docs/components/preview/vf-header.html))

I think some of this ties into the documentation/expected behaviour. 

Given that we have a few different "centering" grids at work (`vf-body`, `vf-header` and the data-protection one), perhaps we evolve the "page grids" category to do something like:
- `vf-body` grid becomes `vf-grid-page-center` for when you want to centre your page
- `vf-header` grid becomes `vf-grid-header` for the header, naturally!
-  `vf-data-protection-banner` grid becomes `vf-grid-data-protection-banner`

**Comment by khawkins98** [comment]
Forgot to finish my thought: the above would open up for "exoctic" variations of `vf-body/vf-grid-page-center`:
- `vf-grid-page-left` for when for some reason you want content fixed to the left
- `vf-grid-narrow-page-center` when you need a really narrow column
- other weird use cases that we can't quite imagine yet

**Comment by khawkins98** [comment]
I think we're pretty aware of this issue space and the conversation here has been fully eclipsed, yes? 

Being bold and closing.
