### ISSUE TITLE
Secondary links too dark for black boxes

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#573]
The `vf-link--secondary` is too dark (not enough contrast) for the aside box text, specially when the link has not yet been visited.
![No visited](https://user-images.githubusercontent.com/8555781/65594242-481f4300-df8a-11e9-95f6-e49ac449f834.png)
![Visited](https://user-images.githubusercontent.com/8555781/65594246-49e90680-df8a-11e9-9fc7-d3fd281bc262.png)

**Comment by sturobson** [comment]
can you provide the HTML for this please :)

**Comment by esanzgar** [comment]
```
<aside class="vf-inlay__content--additional">
    <div class="vf-box">
        <h3 class="vf-box__heading">Problems Signing?</h3>
        <p class="vf-box__text">If you have problems signing using your EMBL-EBI username and password <a href="mailto:itsupport@ebi.ac.uk" class="vf-link--secondary">contact the IT helpdesk</a>.</p>
    </div>
</aside>
```

https://wwwint.ebi.ac.uk/my-account

**Comment by sturobson** [comment]
I'm not sure this wouldn't make much difference here, but `vf-link--secondary` needs `vf-link` too.

I'm assuming you're not using `vf-link--primary` because of it's colouring? 

I'll have a think on this. As the `vf-link` is nested inside some `vf-box__text` perhaps it would be better to consider `color: inherit` or similar (although we'd still need to look at the pseudo classes).

**Comment by sturobson** [comment]
This should be resolved now as we make decisions on colour in `vf-box` so a link would have the `currentColor` of the `vf-box` that has been defined in `vf-box-theme--primary/seoncdary/tertiary` 

Closing this as it should be fixed (and appears to be on a quick test of the HTML provided) and it's v. v. old.

Please open again if there are other related issues
