### ISSUE TITLE
ENHANCEMENT - vf-video aspect ratio

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#641]
currently the `vf-video` component is ready for a 16:9 aspect ration video. There's a chance (and request) for this component to support 4:3 ratios also. 

- is there a way to do this 'automagically' with CSS? (object-fit?)
- should we have a default `vf-video` and then have two variants `vf-video--169`/`vf-video--43`

**Comment by dbushell** [comment]
use case: https://github.com/visual-framework/vf-wp/issues/80

**Comment by dbushell** [comment]
I've been playing around with an implementation:

```nunjucks
<div class="vf-video"{% if padding %} style="padding-bottom: {{ padding }}%"{% endif %}>
    <iframe width="{{ width }}" height="{{ height }}" src="{{ src }}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>
```

The template needs updating to include dimension variables. I've temporarily added inline style for padding (to allow custom ratios). Not ideal as it requires more template logic, maybe there is an "automagically" solution.

I'd like to be able to support a maximum width. Right now I'd have to do something like:

```nunjucks
<div style="max-width: 320px">
  <div class="vf-video"> ... </div>
</div>
```

It requires an outer-wrapper, otherwise the padding is wrong. Don't think I can use `max-width` on `vf-video` or `iframe` unless there is a different technique than the intrinsic ratio.

**Comment by dbushell** [comment]
Noticed `vf-video` has a `padding-top: 25px;` in the core CSS. Is there a reason for this? It makes the ratio slightly off when combined with `padding-bottom`.

**Comment by dbushell** [comment]
Some CSS to allow max width without extra wrappers:

```css
--vf-video-max-width: 320px;
max-width: var(--vf-video-max-width);
padding-bottom: calc(9 / 16 * (100% - (100% - var(--vf-video-max-width))));
```

Basically substracting the difference from the padding. Maybe there is some algebraic solution to clean that up, my math sucks.

**Comment by sturobson** [comment]
After discussing this in Slack:

There's this one odd service that brings it's own thing to the party (and around 3.5mb of data) when embedded into the page, Panopto - https://embl-ebi.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=92c4b9b2-2d6b-479a-bb40-a99100a59f91&v=2

It's more a case of the potential need for e more generic `vf-embed` component that can handle:

- ratio
- max-width
- setting heigh/width

At the moment, as the Panopto embed is more a 'one-off'. The `vf-embed` component will be extended inside of `vf-wp` to accommodate. 

`vf-embed` could really still do with `--16x9` and `--4x3` modifiers to allow for the two most used ratios for video formats.
