### ISSUE TITLE
STRATEGIC - Fallback support should be IE only

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#734]
Proposal is that we make our life much simpler if we're plain by making our support policy and Sass code for fallback support specific to IE 11.

That is, everyone else gets "modern" code. And we have IE 11 specific support:

```css
// IE 10/11 only fixes
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
}
```

And that support is mostly (only?) for:

- Grid alternatives
- CSS custom property alternatives

--- 

### CSS Grid
- https://caniuse.com/#feat=css-grid

Non-supporting versions and our users (for the month of november):

Browser | Last unsupported version | Sessions | Session % of total
-- | -- | -- | --
Internet Explorer | 11 | 3,758 | 2.79%
Safari | 10 | 263 | 0.20%
Edge | 15 | 112 | 0.08%
Firefox | 51 | 1,081 | 0.80%
Chrome | 56 | 0 | 0.00%
Opera | 43 | 17 | 0.01%
Android Webview | 79 | 833 | 0.62%

### CSS Custom props

- https://caniuse.com/#feat=css-variables

Non-supporting versions and our users:

Browser | Last unsupported version | Sessions | Session % of total
-- | -- | -- | --
Internet Explorer | 11 | 3,758 | 2.79%
Safari | 9.2 | 138 | 0.10%
Edge | 15 | 112 | 0.08%
Firefox | 30 | 13 | 0.01%
Chrome | 48 | 0 | 0.00%
Opera | 35 | 17 | 0.01%
Android Webview | 79 | 833 | 0.62%

Source: https://docs.google.com/spreadsheets/d/1WO_sZNmJgMIouPVjW_YIKKeaNjhW7JO-FdppQ8jEIx0/edit#gid=1722401397

**Comment by khawkins98** [comment]
It's arguable to also support FF 46-51, but things already look broke there with our attempts at supporting "all" non-grid browsers. So IE11 might be the most realistic/honest legacy support we can offer without additional development support.

**Comment by sturobson** [comment]
This one might stretch out to a much wider issue of 'support policy' for when authoring components and designing / developing vf-core for the web.

Chances are, I might amend this comment as–and–when. I'll include a précis of the updates, if so.

## Layout 

When we create a new component that needs layout to be written in CSS grid we should make use of the `@supports` query – `@supports (display: grid) { … }`. Doing this allows us to create a similar or alternative layout in CSS flexbox first and, if supported, let the browser use grid. 

This might be handy for the few instances I've also seen where `subgrid` would make things 'nicer' on the page, where we could use `@supports (display: subgrid) { … }`.

## Custom Properties

These are a bit 'it depends'. If they're wrapped up in a ruleset for declaring layout with CSS grid, we don't need to provide a fallback, as this should be rectified with the flexbox alternative. 

Rather than duplicating CSS, because of non-supporting browsers, I have been leaning to setting a default of black or white (depending on the design) and then enhancing them with custom properties for theming with `--primary`, `--secondary` and so forth. 

## The IE media query and support

I think that we should wrap
```
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
...
}
```

inside a Sass mixin using the `@contents` directive so that we don't have to a) copy and paste the media query b) try and type it correctly each time. This should be a 'last try' as the fix we are adding, could probably be something that other older browsers should. 

## Supporting other old browsers

The content should be at least accessible, in my opinion that doesn't mean it should look the same. If the browser does not support flexbox - then, the hope is that, is should be one massive mobile viewport chunk of a page.

**Comment by khawkins98** [comment]
From a code readability/maintenance perspective, it would be nice if the compatibility stuff was a bit easier to find; I think we could do that any number of ways:

1. `background: green; // Custom properties compatibility code`
     - Probably the closest to what we're doing now 
2. `vf-component.compatibility.scss`
    - Would make things a bit easier to diagnose, but probably make maintenance more of a chore. 
2. `/* Compatibility code section below */`
    - Probably not a great compromise of the 2 above options
