### ISSUE TITLE
Table component required in VF

### ISSUE THREAD

**Issue by gabsie** [visual-framework/vf-core#856]
Needed for these occasions:
https://invis.io/PAWQQBPYXW5#/413504329_Sequences_-_Projects
https://chanzuckerberg.invisionapp.com/share/DMWL3W8FG42#/413516442_4-1-1_Contribute-My_Projects_Copy_2

Additionally, I need:
 - sorting arrows
 - proper checkboxes
 - and following - ability to do bulk actions with selected things from the table, so similarly to the bulk download presented, however there may be a better display and also - maybe a dropdown with more actions in the future.
 - action links - Edit | Delete e.g. of an entry
 - status - Draft \ Complete \ In Pipeline e.g.

I am here for questions :)
HCA are eager to have it..

**Comment by sturobson** [comment]
Hey! 

We have made a quick start on tables which are currently available (to look at) on [this page of the component library](https://visual-framework.github.io/vf-core/components/detail/vf-table.html). 

We are hoping to push the necessary code to NPM today/tomorrow so that they can start to be used as they currently are.

I'll take a look at your other requirements you've mentioned that we don't have and get back to you.

We also have #852 where I'll be working from in getting all the things into tables as needed.

**Comment by gabsie** [comment]
Perfect, Stu!

I think I missed a major one in the original request - we need some action links, and possibly statuses
I'll add them there! Thanks!!!

Gabs
