### ISSUE TITLE
QUESTION: Should we refactor to include a global reset or normalise CSS component

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#983]
1. Originally we had a 'component' that would include the CSS reset at the start of the CSS to give us some good defaults to work upon.

2. This kinda broke when using VF2.x with VF1.x components, sites and pages so we removed it and move any reset CSS needed to the components as needed.

3. The more we integrate with `vf-wp` and how 'WordPress does things" with CSS the more there is a need for a default 'reset' from `vf-core`

4. Because we are adding resets per component. We are adding lots of lines of CSS that we could reduce with a CSS reset component.

5. Doing this and creating a VF2.x reset - would move the onus on older codebases to either 'fix' any issues that the CSS reset gives them - or completely update to VF2.x (hah!)

**Comment by sumit-mann** [comment]
@sturobson just going through this project and saw this question. 

I think there should be no reset or normalise css when thinking about UI patterns as components.

Creating a reset css component and then using it in the component will require lots of logic like only required reset css comes to component not the complete reset styles. importing reset css component in each component will only make it redundant.


As a component should be self contained only few line are sufficient to normalise default styling.
Even if the complete library is used, instead of single component, the minification tools can take care of extra few line written in each component. so there'll be not much difference in minified css as compared to adding a global reset css.

I hope above points will help :)
